# Generated by Django 5.0.2 on 2024-05-08 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('projects', '0005_alter_bimmodel_bim_project_alter_bimmodel_designer'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='specification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='organization.bimspecification', verbose_name='specifica coordinamento/verifica'),
        ),
    ]
