# Generated by Django 5.0.2 on 2024-05-08 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_report_specification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validationtest',
            name='specification',
        ),
    ]
