# Generated by Django 5.0.2 on 2024-05-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_validationtest_specification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bimproject',
            name='description',
            field=models.CharField(default='0000000', max_length=150, verbose_name='descrizione'),
        ),
    ]
