# Generated by Django 5.0.2 on 2024-05-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_bimproject_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bimproject',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='descrizione'),
        ),
    ]
