# Generated by Django 5.0.2 on 2024-05-08 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('projects', '0009_alter_bimproject_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bimmodel',
            name='authoringSoftware',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='bim_models', to='organization.authoringsoftware', verbose_name='software di authoring'),
        ),
        migrations.AlterField(
            model_name='bimmodel',
            name='bim_coordinator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='bim_coordinator_role_models', to='organization.bimexpert', verbose_name='bim coordinator'),
        ),
        migrations.AlterField(
            model_name='bimmodel',
            name='bim_manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='bim_manager_role_models', to='organization.bimexpert', verbose_name='bim manager'),
        ),
        migrations.AlterField(
            model_name='bimmodel',
            name='bim_specialist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='bim_specialist_role_models', to='organization.bimexpert', verbose_name='bim specialist'),
        ),
        migrations.AlterField(
            model_name='bimmodel',
            name='description',
            field=models.CharField(default='-', max_length=150, verbose_name='descrizione'),
        ),
        migrations.AlterField(
            model_name='bimmodel',
            name='designer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='designer_role_models', to='organization.bimexpert', verbose_name='progettista'),
        ),
        migrations.AlterField(
            model_name='bimmodel',
            name='discipline',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='bim_models', to='organization.discipline', verbose_name='disciplina'),
        ),
        migrations.AlterField(
            model_name='bimmodel',
            name='lodReference',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='bim_models', to='organization.lodreference', verbose_name='scheda LOD'),
        ),
    ]
