# Generated by Django 5.2.13 on 2026-05-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_bimmodel_bim_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bimmodel',
            name='description',
            field=models.CharField(default='-', max_length=150, verbose_name='descrizione'),
        ),
        migrations.AlterField(
            model_name='infosheet',
            name='description',
            field=models.CharField(default='-', max_length=150, verbose_name='descrizione'),
        ),
        migrations.AlterField(
            model_name='infosheet',
            name='name',
            field=models.CharField(max_length=50, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.CharField(default='-', max_length=150, verbose_name='descrizione'),
        ),
        migrations.AlterField(
            model_name='report',
            name='name',
            field=models.CharField(max_length=50, verbose_name='nome'),
        ),
    ]
