name: BIM-project-manager

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: django-image
    container_name: django-container
    ports: 
      - "8000:8000"
    volumes:
      - .:/app

  db:
    image: postgres:18
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
      POSTGRES_DB: my_database
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - "5432:5432"

volumes:
  postgres_data:
