# Generated by Django 5.0.2 on 2024-05-10 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discipline',
            name='code',
        ),
    ]
