# Generated by Django 5.2.13 on 2026-05-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_remove_discipline_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authoringsoftware',
            name='version',
        ),
        migrations.RemoveField(
            model_name='bimexpert',
            name='position',
        ),
        migrations.AddField(
            model_name='authoringsoftware',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='descrizione'),
        ),
        migrations.AddField(
            model_name='bimexpert',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='descrizione'),
        ),
    ]
