# Generated by Django 5.0.2 on 2024-04-26 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bimexpert',
            options={'verbose_name': 'Professionista', 'verbose_name_plural': 'Professionisti'},
        ),
        migrations.AddField(
            model_name='discipline',
            name='code',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='codice disiplina'),
        ),
    ]
