# Generated by Django 5.0.2 on 2024-04-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_bimexpert_options_discipline_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='BimSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='nome')),
                ('description', models.CharField(blank=True, max_length=150, null=True, verbose_name='descrizione')),
            ],
            options={
                'verbose_name': 'Specifica coordinamento/verifica',
                'verbose_name_plural': 'Specifiche coordinamento/verifica',
            },
        ),
    ]
