# Generated by Django 5.0.2 on 2024-02-24 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BimModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('discipline', models.CharField(blank=True, max_length=50, null=True)),
                ('designer', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Modello',
                'verbose_name_plural': 'Modelli',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('logo_img', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Progetto',
                'verbose_name_plural': 'Progetti',
            },
        ),
        migrations.CreateModel(
            name='InfoSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('bim_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_sheets', to='projects.bimmodel')),
            ],
            options={
                'verbose_name': 'Scheda informativa',
                'verbose_name_plural': 'Schede informative',
            },
        ),
        migrations.AddField(
            model_name='bimmodel',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bim_models', to='projects.project'),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('info_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='projects.infosheet')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
            },
        ),
        migrations.CreateModel(
            name='ClashTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comments', models.CharField(blank=True, max_length=150, null=True)),
                ('clash_new', models.PositiveIntegerField()),
                ('clash_active', models.PositiveIntegerField()),
                ('clash_reviewed', models.PositiveIntegerField()),
                ('clash_approved', models.PositiveIntegerField()),
                ('clash_resolved', models.PositiveIntegerField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clash_tests', to='projects.report')),
            ],
            options={
                'verbose_name': 'Clash Test',
                'verbose_name_plural': 'Clash Tests',
            },
        ),
        migrations.CreateModel(
            name='ValidationTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comments', models.CharField(blank=True, max_length=150, null=True)),
                ('specification', models.CharField(blank=True, max_length=100, null=True)),
                ('issues', models.PositiveIntegerField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_tests', to='projects.report')),
            ],
            options={
                'verbose_name': 'Validation Test',
                'verbose_name_plural': 'Validation Tests',
            },
        ),
    ]
