# Generated by Django 5.0.2 on 2024-02-29 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infosheet',
            name='sheet_type',
            field=models.CharField(default='test', max_length=20),
            preserve_default=False,
        ),
    ]
