# Generated by Django 5.0.2 on 2024-05-08 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('projects', '0002_alter_bimproject_default_bim_coordinator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bimmodel',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='descrizione'),
        ),
        migrations.AlterField(
            model_name='bimmodel',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='organization.discipline', verbose_name='disciplina'),
        ),
        migrations.AlterField(
            model_name='bimmodel',
            name='name',
            field=models.CharField(max_length=50, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='bimproject',
            name='default_bim_coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bim_coordinator_role_projects', to='organization.bimexpert', verbose_name='bim coordinator progetto'),
        ),
        migrations.AlterField(
            model_name='bimproject',
            name='default_bim_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bim_manager_role_projects', to='organization.bimexpert', verbose_name='bim manager progetto'),
        ),
        migrations.AlterField(
            model_name='bimproject',
            name='default_bim_specialist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bim_specialist_role_projects', to='organization.bimexpert', verbose_name='bim specialist progetto'),
        ),
        migrations.AlterField(
            model_name='bimproject',
            name='default_designer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designer_role_projects', to='organization.bimexpert', verbose_name='responsabile progetto'),
        ),
    ]
