# Generated by Django 5.0.2 on 2024-03-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_infosheet_sheet_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationtest',
            name='specification',
            field=models.CharField(default='prova', max_length=100),
            preserve_default=False,
        ),
    ]
