# Generated by Django 5.0.2 on 2024-03-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_validationtest_specification'),
    ]

    operations = [
        migrations.AddField(
            model_name='bimmodel',
            name='default_coordination',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bimmodel',
            name='default_validation',
            field=models.BooleanField(default=False),
        ),
    ]
