# Generated by Django 5.0.2 on 2024-05-08 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('projects', '0003_bimmodel_description_alter_bimmodel_discipline_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bimmodel',
            old_name='project',
            new_name='bim_project',
        ),
        migrations.AddField(
            model_name='bimmodel',
            name='bim_coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bim_coordinator_role_models', to='organization.bimexpert', verbose_name='bim coordinator'),
        ),
        migrations.AddField(
            model_name='bimmodel',
            name='bim_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bim_manager_role_models', to='organization.bimexpert', verbose_name='bim manager'),
        ),
        migrations.AddField(
            model_name='bimmodel',
            name='bim_specialist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bim_specialist_role_models', to='organization.bimexpert', verbose_name='bim specialist'),
        ),
        migrations.AlterField(
            model_name='bimmodel',
            name='authoringSoftware',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bim_models', to='organization.authoringsoftware', verbose_name='software di authoring'),
        ),
        migrations.AlterField(
            model_name='bimmodel',
            name='designer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designer_role_models', to='organization.authoringsoftware', verbose_name='progettista'),
        ),
        migrations.AlterField(
            model_name='bimmodel',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bim_models', to='organization.discipline', verbose_name='disciplina'),
        ),
        migrations.AlterField(
            model_name='bimmodel',
            name='lodReference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bim_models', to='organization.lodreference', verbose_name='scheda LOD'),
        ),
    ]
