# Generated by Django 5.0.2 on 2024-03-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_bimmodel_default_coordination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bimmodel',
            name='authoringSoftware',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bimmodel',
            name='lodReference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
