# Generated by Django 5.0.2 on 2024-05-08 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('projects', '0004_rename_project_bimmodel_bim_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bimmodel',
            name='bim_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bim_models', to='projects.bimproject', verbose_name='progetto'),
        ),
        migrations.AlterField(
            model_name='bimmodel',
            name='designer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designer_role_models', to='organization.bimexpert', verbose_name='progettista'),
        ),
    ]
