# Generated by Django 5.0.2 on 2024-03-25 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_bimmodel_authoringsoftware_bimmodel_lodreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='bimproject',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='bimproject',
            name='customer',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='bimproject',
            name='phase',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
