# Generated by Django 5.0.2 on 2024-03-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_bimproject_address_alter_bimproject_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bimmodel',
            name='authoringSoftware',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='software di authoring'),
        ),
        migrations.AlterField(
            model_name='bimmodel',
            name='designer',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='progettista'),
        ),
        migrations.AlterField(
            model_name='bimmodel',
            name='discipline',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='disciplina'),
        ),
        migrations.AlterField(
            model_name='bimmodel',
            name='lodReference',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='scheda LOD'),
        ),
        migrations.AlterField(
            model_name='bimmodel',
            name='name',
            field=models.CharField(max_length=80, verbose_name='nome'),
        ),
    ]
