# Generated by Django 5.0.2 on 2024-03-26 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_bimmodel_authoringsoftware_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infosheet',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='disciplina'),
        ),
        migrations.AlterField(
            model_name='infosheet',
            name='name',
            field=models.CharField(max_length=80, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='infosheet',
            name='sheet_type',
            field=models.CharField(max_length=20, verbose_name='tipo scheda'),
        ),
    ]
