# Generated by Django 5.0.2 on 2024-05-08 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('projects', '0010_alter_bimmodel_authoringsoftware_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bimmodel',
            name='bim_project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bim_models', to='projects.bimproject', verbose_name='progetto'),
        ),
        migrations.AlterField(
            model_name='bimmodel',
            name='description',
            field=models.CharField(max_length=150, verbose_name='descrizione'),
        ),
        migrations.AlterField(
            model_name='bimproject',
            name='address',
            field=models.CharField(default='-', max_length=150, verbose_name='indirizzo'),
        ),
        migrations.AlterField(
            model_name='bimproject',
            name='customer',
            field=models.CharField(default='-', max_length=50, verbose_name='committente'),
        ),
        migrations.AlterField(
            model_name='bimproject',
            name='default_bim_coordinator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='bim_coordinator_role_projects', to='organization.bimexpert', verbose_name='bim coordinator progetto'),
        ),
        migrations.AlterField(
            model_name='bimproject',
            name='default_bim_manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='bim_manager_role_projects', to='organization.bimexpert', verbose_name='bim manager progetto'),
        ),
        migrations.AlterField(
            model_name='bimproject',
            name='default_bim_specialist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='bim_specialist_role_projects', to='organization.bimexpert', verbose_name='bim specialist progetto'),
        ),
        migrations.AlterField(
            model_name='bimproject',
            name='default_designer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='designer_role_projects', to='organization.bimexpert', verbose_name='responsabile progetto'),
        ),
        migrations.AlterField(
            model_name='bimproject',
            name='description',
            field=models.CharField(default='-', max_length=150, verbose_name='descrizione'),
        ),
        migrations.AlterField(
            model_name='bimproject',
            name='phase',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='projects', to='organization.projectphase', verbose_name='fase progettuale'),
        ),
        migrations.AlterField(
            model_name='clashtest',
            name='comments',
            field=models.CharField(default='-', max_length=150, verbose_name='commenti'),
        ),
        migrations.AlterField(
            model_name='infosheet',
            name='description',
            field=models.CharField(default='-', max_length=150, verbose_name='disciplina'),
        ),
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.CharField(default='-', max_length=150, verbose_name='descrizione report'),
        ),
        migrations.AlterField(
            model_name='report',
            name='specification',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='reports', to='organization.bimspecification', verbose_name='specifica coordinamento/verifica'),
        ),
        migrations.AlterField(
            model_name='validationtest',
            name='comments',
            field=models.CharField(default='-', max_length=150, verbose_name='commenti'),
        ),
    ]
