# Generated by Django 5.0.2 on 2024-05-10 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_bimmodel_bim_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bimmodel',
            name='bim_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bim_models', to='projects.bimproject', verbose_name='progetto'),
        ),
    ]
